=== openilabs/ilabproject-code/PartnerLabs/MIT/WebLabElvis/labserver/www/xml/labConfiguration.dtd
<!ELEMENT labConfiguration (setup*)>
<!ATTLIST labConfiguration	lab			CDATA	#REQUIRED
							specversion	CDATA	#REQUIRED>
	<!ELEMENT setup (name, description, imageURL, terminal+, maxDataPoints)>
	<!ATTLIST setup id		CDATA		#REQUIRED>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT description (#PCDATA)>
		<!ELEMENT imageURL (#PCDATA)>
		<!ELEMENT terminal (label, pixelLocation>
		<!ATTLIST terminal	instrumentType	(FGEN | SCOPE)	#REQUIRED
							instrumentNumber	CDATA	#REQUIRED>
			<!ELEMENT label (#PCDATA)>
			<!ELEMENT pixelLocation (x, y)>
				<!ELEMENT x (#PCDATA)>
				<!ELEMENT y (#PCDATA)>

=== openilabs/ilabproject-code/PartnerLabs/MIT/WebLabElvis/src/labserver/xml/labConfiguration.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE labConfiguration SYSTEM "http://ilab-labview.mit.edu/LabServer/xml/labConfiguration.dtd">
<labConfiguration lab="MIT ELVIS Weblab" specversion="0.1">
	<setup id="5">
		<name>OpAmp Differentiator Circuit</name>
		<description>Aren't opAmpss just swell?</description>
		<imageURL>http://localhost/labServer/setupImages/opAmpDifferentiator.gif</imageURL>
		<terminal instrumentType="FGEN" instrumentNumber="1">
			<label>Input Waveform</label>
			<pixelLocation>
				<x>121</x>
				<y>94</y>
			</pixelLocation>
		</terminal>
		<terminal instrumentType="SCOPE" instrumentNumber="2">
			<label>Oscilloscope</label>
			<pixelLocation>
				<x>195</x>
				<y>156</y>
			</pixelLocation>
		</terminal>
	</setup>
</labConfiguration>
