=== openilabs/ilabproject-code/PartnerLabs/MIT/WebLab/labserver/www/xml/experimentSpecification.dtd
<!-- 
Copyright (c) 2005 The Massachusetts Institute of Technology. All rightsreserved.
Please see license.txt in top level directory for full license. 
-->

<!ELEMENT experimentSpecification (deviceID, terminal+, userDefinedFunction*)>
<!ATTLIST experimentSpecification	lab			CDATA	#REQUIRED
									specversion	CDATA	#REQUIRED>
	<!ELEMENT deviceID (#PCDATA)>
	<!ELEMENT terminal (vname, ((iname, mode, function, compliance?) |
								(function, compliance?) |
								(mode))?)>
	<!ATTLIST terminal	portType	(SMU | VSU | VMU)	#REQUIRED
						portNumber	CDATA				#REQUIRED>
		<!ELEMENT vname (#PCDATA)>
		<!ATTLIST vname	download (true | false) #REQUIRED>
		<!ELEMENT iname (#PCDATA)>
		<!ATTLIST iname download (true | false) #REQUIRED>
		<!ELEMENT mode (#PCDATA)>
		<!ELEMENT function ((scale?, start, stop, step) |
							(offset, ratio) |
							(value))>
		<!ATTLIST function	type	(VAR1 | VAR2 | VAR1P | CONS)	#REQUIRED>
			<!ELEMENT scale (#PCDATA)>
			<!ELEMENT start (#PCDATA)>
			<!ELEMENT stop (#PCDATA)>
			<!ELEMENT step (#PCDATA)>
			<!ELEMENT offset (#PCDATA)>
			<!ELEMENT ratio (#PCDATA)>
			<!ELEMENT value (#PCDATA)>
		<!ELEMENT compliance (#PCDATA)>
	<!ELEMENT userDefinedFunction (name, units, body)>
		<!ELEMENT name (#PCDATA)>
		<!ATTLIST name download (true | false) #REQUIRED>
		<!ELEMENT units (#PCDATA)>
		<!ELEMENT body (#PCDATA)>

=== openilabs/ilabproject-code/PartnerLabs/MIT/WebLab/labserver/www/xml/experimentSpecification.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!DOCTYPE experimentSpecification SYSTEM "http://weblab2.mit.edu/xml/experimentSpecification.dtd">
<experimentSpecification lab="MIT Microelectronics Weblab" specversion="0.1">
	<deviceID>1</deviceID>
	<terminal portType="SMU" portNumber="1">
		<vname download="true">VDS</vname>
		<iname download="true">IDS</iname>
		<mode>V</mode>
		<function type="VAR2">
			<scale>LIN</scale>
			<start>0.05</start>
			<stop>0.5</stop>
			<step>0.1</step>
		</function>
		<compliance>0.1</compliance>
	</terminal>
	<terminal portType="SMU" portNumber="2">
		<vname download="true">VG</vname>
		<iname download="true">IG</iname>
		<mode>V</mode>
		<function type="VAR1">
			<scale>LIN</scale>
			<start>0.0</start>
			<stop>4.5</stop>
			<step>0.05</step>
		</function>
		<compliance>0.1</compliance>
	</terminal>
	<terminal portType="SMU" portNumber="3">
		<vname download="true">VGRD</vname>
		<iname download="true">IGRD</iname>
		<mode>V</mode>
		<function type="CONS">
			<value>0.0</value>
		</function>
		<compliance>0.1</compliance>
	</terminal>
	<userDefinedFunction>
		<name download="true">SQRTID</name>
		<units>A</units>
		<body>SQRT(IDS)</body>
	</userDefinedFunction>
</experimentSpecification>
