=== openilabs/ilabproject-code/LabServer/Radioactivity/LabServer/Xml/LabConfiguration.dtd
<!ELEMENT labConfiguration (navmenuPhoto, labInfo, configuration, validation, experimentSpecification, experimentResult, resultsApplet)>
<!ATTLIST labConfiguration title CDATA #REQUIRED version CDATA #REQUIRED>

<!ELEMENT navmenuPhoto (image)>
<!ELEMENT image (#PCDATA)>

<!ELEMENT labInfo (text, url)>
<!ELEMENT text (#PCDATA)>
<!ELEMENT url (#PCDATA)>

<!ELEMENT configuration (setup+, sources, absorbers, distances)>
<!ELEMENT setup (name, description, distance, duration, repeat)>
<!ATTLIST setup id CDATA #REQUIRED>
<!ELEMENT name (#PCDATA)>
<!ELEMENT description (p*)>
<!ELEMENT p (#PCDATA)>
<!ELEMENT distance (#PCDATA)>
<!ELEMENT duration (#PCDATA)>
<!ELEMENT repeat (#PCDATA)>

<!ELEMENT sources (source+)>
<!ATTLIST sources default CDATA #REQUIRED>
<!ELEMENT source (name, location)>
<!ELEMENT location (#PCDATA)>

<!ELEMENT absorbers (absorber+)>
<!ATTLIST absorbers default CDATA #REQUIRED>
<!ELEMENT absorber (name, location)>

<!ELEMENT distances (minimum, maximum, stepsize)>
<!ELEMENT minimum (#PCDATA)>
<!ELEMENT maximum (#PCDATA)>
<!ELEMENT stepsize (#PCDATA)>

<!ELEMENT validation (vdnDistance, vdnDuration, vdnRepeat, vdnTotaltime)>
<!ELEMENT vdnDistance (minimum, maximum)>
<!ELEMENT vdnDuration (minimum, maximum)>
<!ELEMENT vdnRepeat (minimum, maximum)>
<!ELEMENT vdnTotaltime (minimum, maximum)>

<!ELEMENT experimentSpecification (setupId,
  sourceName, absorberName, distance, duration, repeat)>
<!ELEMENT setupId (#PCDATA)>

<!ELEMENT experimentResult (timestamp, title, version, experimentId, unitId, setupId, setupName,
  sourceName, absorberName, distance, duration, repeat, dataVector)>
<!ELEMENT timestamp (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT experimentId (#PCDATA)>
<!ELEMENT unitId (#PCDATA)>
<!ELEMENT setupName (#PCDATA)>
<!ELEMENT sourceName (#PCDATA)>
<!ELEMENT absorberName (#PCDATA)>
<!ELEMENT dataVector (#PCDATA)>

<!ELEMENT resultsApplet (archive, code)>
<!ELEMENT archive (#PCDATA)>
<!ELEMENT code (#PCDATA)>

=== openilabs/ilabproject-code/LabServer/Radioactivity/LabServer/App_Data/LabConfiguration2.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!--<!DOCTYPE labConfiguration SYSTEM "LabConfiguration.dtd">-->
<labConfiguration title="Radioactivity" version="3.1">
  <navmenuPhoto>
    <image>~/images/radioactivity.jpg</image>
  </navmenuPhoto>
  <labInfo>
    <text />
    <url />
  </labInfo>
  <configuration>
    <setup id="RadioactivityVsTime">
      <name>Radioactivity over Time</name>
      <description>
        <p>Measure radioactivity over time at a fixed distance from the source.</p>
      </description>
      <distance>30</distance>
      <duration>5</duration>
      <repeat>3</repeat>
    </setup>
    <setup id="RadioactivityVsDistance">
      <name>Radioactivity versus Distance</name>
      <description>
        <p>Measure radioactivity at various distances from the source.</p>
      </description>
      <distance>20,25,30,40,65</distance>
      <duration>5</duration>
      <repeat>3</repeat>
    </setup>
    <setup id="SimActivityVsTime">
      <name>Radioactivity over Time (Simulated)</name>
      <description>
        <p>Measure radioactivity over time at a fixed distance from a simulated source.</p>
      </description>
      <distance>20</distance>
      <duration>5</duration>
      <repeat>3</repeat>
    </setup>
    <setup id="SimActivityVsDistance">
      <name>Radioactivity versus Distance (Simulated)</name>
      <description>
        <p>Measure radioactivity at various distances from a simulated source.</p>
      </description>
      <distance>20,25,30,40,65</distance>
      <duration>5</duration>
      <repeat>3</repeat>
    </setup>
    <setup id="SimActivityVsTimeNoDelay">
      <name>Radioactivity over Time (Simulated - No delays)</name>
      <description>
        <p>Measure radioactivity over time at a fixed distance from a simulated source. Equipment operation delays are not included.</p>
      </description>
      <distance>20</distance>
      <duration>5</duration>
      <repeat>3</repeat>
    </setup>
    <setup id="SimActivityVsDistanceNoDelay">
      <name>Radioactivity versus Distance (Simulated - No delays)</name>
      <description>
        <p>Measure radioactivity at various distances from a simulated source. Equipment operation delays are not included.</p>
      </description>
      <distance>20,25,30,40,65</distance>
      <duration>5</duration>
      <repeat>3</repeat>
    </setup>
    <sources default="Strontium-90">
      <source>
        <name>None</name>
        <location>F</location>
      </source>
      <source>
        <name>Strontium-90</name>
        <location>A</location>
      </source>
    </sources>
    <absorbers default="None">
      <absorber>
        <name>None</name>
        <location>A</location>
      </absorber>
      <absorber>
        <name>Nothing</name>
        <location>B</location>
      </absorber>
      <absorber>
        <name>Ziltch</name>
        <location>C</location>
      </absorber>
      <absorber>
        <name>Nought</name>
        <location>D</location>
      </absorber>
      <absorber>
        <name>Empty</name>
        <location>E</location>
      </absorber>
      <absorber>
        <name>Void</name>
        <location>F</location>
      </absorber>
      <absorber>
        <name>Zippo</name>
        <location>G</location>
      </absorber>
      <absorber>
        <name>Not a thing</name>
        <location>H</location>
      </absorber>
      <absorber>
        <name>Still nothing</name>
        <location>I</location>
      </absorber>
      <absorber>
        <name>Nonexistent</name>
        <location>J</location>
      </absorber>
      <absorber>
        <name>Diddly squat</name>
        <location>K</location>
      </absorber>
      <absorber>
        <name>Blank</name>
        <location>L</location>
      </absorber>
      <absorber>
        <name>Null</name>
        <location>M</location>
      </absorber>
      <absorber>
        <name>Vacant</name>
        <location>N</location>
      </absorber>
    </absorbers>
    <distances>
      <minimum>20</minimum>
      <maximum>100</maximum>
      <stepsize>5</stepsize>
    </distances>
  </configuration>
  <validation>
    <vdnDistance>
      <minimum>19</minimum>
      <maximum>95</maximum>
    </vdnDistance>
    <vdnDuration>
      <minimum>1</minimum>
      <maximum>10</maximum>
    </vdnDuration>
    <vdnRepeat>
      <minimum>1</minimum>
      <maximum>10</maximum>
    </vdnRepeat>
    <vdnTotaltime>
      <minimum>1</minimum>
      <maximum>750</maximum>
    </vdnTotaltime>
  </validation>
  <experimentSpecification>
    <setupId />
    <sourceName />
    <absorberName />
    <distance />
    <duration />
    <repeat />
  </experimentSpecification>
  <experimentResult>
    <timestamp />
    <title />
    <version />
    <experimentId />
    <unitId />
    <setupId />
    <setupName />
    <sourceName />
    <absorberName />
    <distance />
    <duration />
    <repeat />
    <dataType />
    <dataVector />
  </experimentResult>
  <resultsApplet>
    <archive></archive>
    <code></code>
  </resultsApplet>
</labConfiguration>

=== openilabs/ilabproject-code/LabServer/Template/LabServer/App_Data/LabConfiguration.xml
<?xml version="1.0" encoding="utf-8" standalone="no" ?>
<!--<!DOCTYPE labConfiguration SYSTEM "LabConfiguration.dtd">-->
<labConfiguration title="Template" version="3.0">
  <navmenuPhoto>
    <image>~/images/generic_content32.jpg</image>
  </navmenuPhoto>
  <labInfo>
    <text />
    <url />
  </labInfo>
  <configuration>
    <setup id="Equipment">
      <name>Setup for Equipment</name>
      <description>
        <p>Template setup for driving equipment.</p>
      </description>
    </setup>
    <setup id="Simulation">
      <name>Setup for Simulation</name>
      <description>
        <p>Template setup for running a simulation.</p>
      </description>
    </setup>
    <!-- YOUR CODE HERE -->
  </configuration>
  <validation>
    <!-- YOUR CODE HERE -->
  </validation>
  <experimentSpecification>
    <setupId />
    <!-- YOUR CODE HERE -->
  </experimentSpecification>
  <experimentResult>
    <timestamp />
    <title />
    <version />
    <experimentId />
    <unitId />
    <setupId />
    <setupName />
    <!-- YOUR CODE HERE -->
  </experimentResult>
  <resultsApplet>
    <archive></archive>
    <code></code>
  </resultsApplet>
</labConfiguration>
