=== openilabs/ilabproject-code/PartnerLabs/UQueensland/BatchLabServer/Radioactivity/LabEquipment/App_Data/EquipmentConfig.dtd
<!ELEMENT equipmentConfig (hardwarePresent, powerupDelay, powerdownTimeout, flexMotion, serialLcd, radiationCounter, physicsCounter*, st360Counter)>
<!ATTLIST equipmentConfig title CDATA #REQUIRED version CDATA #REQUIRED>
<!ELEMENT flexMotion (boardID, tube, sources, absorbers*, initialiseDelay)>
<!ELEMENT tube (axisId, offsetDistance, homeDistance, moveRate, initAxis)>
<!ELEMENT sources (axisId, encoderPositions, selectTimes, returnTimes, firstLocation, homeLocation)>
<!ELEMENT absorbers (axisId, encoderPositions, selectTimes, returnTimes, firstLocation, homeLocation)>
<!ELEMENT serialLcd (type, network, serial, writeLineTime, initialiseDelay)>
<!ELEMENT network (ipaddr, port)>
<!ELEMENT serial (port, baud)>
<!ELEMENT radiationCounter (type)>
<!ELEMENT st360Counter (type, network, serial, voltage, volume, timeAdjustment, initialiseDelay)>
<!ELEMENT physicsCounter (timeAdjustment, initialiseDelay)>
<!ELEMENT timeAdjustment (capture)>

<!ELEMENT hardwarePresent (#PCDATA)>
<!ELEMENT powerupDelay (#PCDATA)>
<!ELEMENT powerdownTimeout (#PCDATA)>
<!ELEMENT boardID (#PCDATA)>
<!ELEMENT axisId (#PCDATA)>
<!ELEMENT initialiseDelay (#PCDATA)>
<!ELEMENT offsetDistance (#PCDATA)>
<!ELEMENT homeDistance (#PCDATA)>
<!ELEMENT moveRate (#PCDATA)>
<!ELEMENT initAxis (#PCDATA)>
<!ELEMENT encoderPositions (#PCDATA)>
<!ELEMENT selectTimes (#PCDATA)>
<!ELEMENT returnTimes (#PCDATA)>
<!ELEMENT firstLocation (#PCDATA)>
<!ELEMENT homeLocation (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT ipaddr (#PCDATA)>
<!ELEMENT port (#PCDATA)>
<!ELEMENT baud (#PCDATA)>
<!ELEMENT writeLineTime (#PCDATA)>
<!ELEMENT voltage (#PCDATA)>
<!ELEMENT volume (#PCDATA)>
<!ELEMENT capture (#PCDATA)>

=== openilabs/ilabproject-code/PartnerLabs/UQueensland/BatchLabServer/Radioactivity/LabEquipment/App_Data/EquipmentConfig_Radioactivity2.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE equipmentConfig SYSTEM "EquipmentConfig.dtd">
<equipmentConfig title="Radioactivity #2" version="3.2">
  <hardwarePresent>true</hardwarePresent>
  <powerupDelay>10</powerupDelay>
  <powerdownTimeout>1800</powerdownTimeout>
  <flexMotion>
    <boardID>2</boardID>
    <tube>
      <axisId>1</axisId>
      <offsetDistance>9</offsetDistance>
      <homeDistance>20</homeDistance>
      <moveRate>0.530</moveRate>
      <initAxis>true</initAxis>
    </tube>
    <sources>
      <axisId>2</axisId>
      <encoderPositions>72000,82700,7700,23750,39800,55900</encoderPositions>
      <selectTimes>11.2,12.1,5.8,7.4,8.6,9.9</selectTimes>
      <returnTimes>8.6,7.5,13.8,12.6,11.2,9.9</returnTimes>
      <firstLocation>A</firstLocation>
      <homeLocation>F</homeLocation>
    </sources>
    <absorbers>
      <axisId>3</axisId>
      <encoderPositions>3200,9300,15400,21500,27600,33700,39900,46100,52200,58300,64400,70500,76600,83000</encoderPositions>
      <selectTimes>9.4,10.3,11.0,11.5,12.0,12.5,13.0,13.4,13.9,14.4,14.9,15.4,15.9,16.4</selectTimes>
      <returnTimes>9.4,8.9,8.4,7.9,7.5,7.0,6.5,6.0,5.5,5.0,4.5,4.0,3.5,2.7</returnTimes>
      <firstLocation>A</firstLocation>
      <homeLocation>A</homeLocation>
    </absorbers>
    <initialiseDelay>37</initialiseDelay>
  </flexMotion>
  <serialLcd>
    <!--<type>Network</type>-->
    <!--<type>Serial</type>-->
    <type>None</type>
    <network>
      <ipaddr>10.0.3.2</ipaddr>
      <port>10002</port>
    </network>
    <serial>
      <port>COM3</port>
      <baud>19200</baud>
    </serial>
    <writeLineTime>0.22</writeLineTime>
    <initialiseDelay>2</initialiseDelay>
  </serialLcd>
  <radiationCounter>
    <type>ST360</type>
    <!--<type>Physics</type>-->
  </radiationCounter>
  <st360Counter>
    <type>Network</type>
    <!--<type>Serial</type>-->
    <network>
      <ipaddr>10.0.3.2</ipaddr>
      <port>10001</port>
    </network>
    <serial>
      <port>COM4</port>
      <baud>9600</baud>
    </serial>
    <voltage>400</voltage>
    <volume>2</volume>
    <timeAdjustment>
      <capture>1.0625,0.175</capture>
    </timeAdjustment>
    <initialiseDelay>3</initialiseDelay>
  </st360Counter>
</equipmentConfig>
